import JSZip from 'jszip';
import generationReceiptSchema from '../../schemas/mapsoo-generation-receipt.schema.json';
import packSchema from '../../schemas/mapsoo-pack-0.2.schema.json';
import worldSchema from '../../schemas/mapsoo-world.schema.json';
import { assertPlayableTerrainExportEvidence } from '../core/playable-terrain-export-policy';
import type { GenerationRunResult } from '../core/generation-evidence';
import { assertTrustedGenerationRun } from '../core/generation-provider';
import {
  ALPHA4_PACK_VERSION,
  buildAlpha4PackManifest,
} from '../core/pack-manifest-alpha4';
import { assertSafePackPath, type PackFileRecord } from '../core/pack-manifest';
import { projectPlayableTerrain } from '../core/playable-terrain';
import { projectTrustedGenerationReceipt } from '../core/trusted-generation-receipt';
import { validateGeneratedWorld } from '../core/validate-world';
import { encodeCanvasPng } from './canvas/encode-png';
import {
  renderPlayablePropsAtlas,
  renderPlayableTerrainAtlas,
  renderPlayableWorldToCanvas,
} from './canvas/render-playable-world';
import { escapeMarkdownInline, revokeObjectUrlLater } from './export-browser-pack';

interface PayloadEntry {
  readonly path: string;
  readonly bytes: Uint8Array;
  readonly record: PackFileRecord;
}

const ZIP_DATE = new Date(Date.UTC(1980, 0, 1, 0, 0, 0, 0));

function comparePortablePaths(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function jsonBlob(value: unknown): Blob {
  return new Blob([`${JSON.stringify(value, null, 2)}\n`], { type: 'application/json' });
}

function textBlob(value: string, type = 'text/markdown'): Blob {
  return new Blob([value], { type: `${type};charset=utf-8` });
}

async function sha256Bytes(bytes: Uint8Array): Promise<string> {
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);
  const digest = await crypto.subtle.digest('SHA-256', buffer);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

async function payloadEntry(path: string, blob: Blob): Promise<PayloadEntry> {
  const safePath = assertSafePackPath(path);
  const bytes = new Uint8Array(await blob.arrayBuffer());
  return {
    path: safePath,
    bytes,
    record: {
      path: safePath,
      media_type: blob.type.split(';')[0],
      bytes: bytes.byteLength,
      sha256: await sha256Bytes(bytes),
    },
  };
}

function assertExactPayloadCoverage(
  entries: readonly PayloadEntry[],
  records: readonly PackFileRecord[],
): void {
  const entryPaths = entries.map(({ path }) => path).sort();
  const recordPaths = records.map(({ path }) => path).sort();
  if (JSON.stringify(entryPaths) !== JSON.stringify(recordPaths)) {
    throw new Error('Alpha.4 manifest files must cover every payload exactly once.');
  }
}

export function assertAlpha4ExportEvidence(run: GenerationRunResult): void {
  assertPlayableTerrainExportEvidence(
    run,
    `${ALPHA4_PACK_VERSION} portable export requires the exact runner-verified playable terrain evidence profile.`,
  );
}

/**
 * Builds the schema-0.2 playable terrain candidate. Trust and publication
 * policy checks run before Canvas or ZIP creation, and every payload is bound
 * into both the manifest and the canonical generation receipt.
 */
export async function buildAlpha4PortablePack(
  run: GenerationRunResult,
): Promise<{ filename: string; blob: Blob }> {
  assertTrustedGenerationRun(run);
  assertAlpha4ExportEvidence(run);
  const { world } = run;
  const errors = validateGeneratedWorld(world).filter((issue) => issue.severity === 'error');
  if (errors.length > 0) {
    throw new Error(`Invalid generated world: ${errors.map((issue) => issue.code).join(', ')}`);
  }

  const rootName = assertSafePackPath(`mapsoo-${world.spec.id}-v${ALPHA4_PACK_VERSION}`);
  const manifestPath = assertSafePackPath('mapsoo.manifest.json');
  const worldSpecPath = assertSafePackPath(`worlds/${world.spec.id}.world.json`);
  const filename = assertSafePackPath(`${rootName}.zip`);
  const projection = projectPlayableTerrain(world);

  const previewCanvas = document.createElement('canvas');
  renderPlayableWorldToCanvas(previewCanvas, world, world.spec.visual.tileSize);

  const worldBlob = jsonBlob(world.spec);
  const initialPayloads = new Map<string, Blob>([
    ['readme.md', textBlob(
      `# ${escapeMarkdownInline(world.spec.title)}\n\nGenerated by Mapsoo Worldsmith ${ALPHA4_PACK_VERSION}.\n\n- Grid: orthogonal\n- Tile size: ${world.spec.visual.tileSize}px\n- Map: ${world.spec.map.width} × ${world.spec.map.height}\n- Layers: Ground, Water, Roads, Props\n- Godot target: 4.3+\n- Minimum compatible importer: Mapsoo Pack Importer ${ALPHA4_PACK_VERSION}+\n- Asset license: CC0-1.0\n- Pack graphics use generative AI: no\n- Pack schema: 0.2.0\n- Generation receipt: 0.2.0\n\n## Godot quick start\n\n1. Install **Mapsoo Pack Importer** from the official repository: https://github.com/babyrush0101-source/mapsoo-kids\n2. Extract this data pack.\n3. In Godot choose **Project → Tools → Import Mapsoo Pack...** and select the extracted \`mapsoo.manifest.json\`.\n4. Open the generated scene under \`res://mapsoo_imports/${world.spec.id}/\`.\n\nThe imported TileSet includes separate match-sides terrain sets for Water and Roads. Water tiles have full-cell blocking collision on the \`world-blocking\` physics layer. The demo scene uses explicit tile IDs, so its first import is deterministic.\n\n## Security boundary\n\nThis asset pack intentionally contains no executable GDScript or addon. Do not enable scripts copied from a third-party asset pack. SHA-256 records verify pack consistency, not publisher identity.\n\nPNG and JSON remain the portable source of truth; the separately installed importer derives Godot resources inside the editor.\n`,
    )],
    ['license-assets.md', textBlob(
      '# Pack license map\n\n## CC0-1.0 assets\n\nThe procedural PNG and map assets in this pack are dedicated to the public domain under CC0 1.0. This notice does not cover user-imported or future third-party/AI-provider assets.\n\n## MIT-licensed bundled files\n\nThe bundled `readme.md` and files under `schema/` are distributed under the following MIT License. The copyright and permission notice must remain with copies of those files.\n\nCopyright (c) 2026 babyrush0101-source\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
    )],
    [worldSpecPath, worldBlob],
    ['worlds/demo-world.json', jsonBlob({
      schema_version: '0.2.0',
      width: projection.width,
      height: projection.height,
      layers: projection.layers.map(({ id, cells }) => ({ id, encoding: 'row-major', cells })),
      props: world.props,
    })],
    ['atlases/terrain.png', encodeCanvasPng(renderPlayableTerrainAtlas(world))],
    ['atlases/props.png', encodeCanvasPng(renderPlayablePropsAtlas(world))],
    ['previews/map-preview.png', encodeCanvasPng(previewCanvas)],
    ['schema/mapsoo-pack-0.2.schema.json', jsonBlob(packSchema)],
    ['schema/mapsoo-world.schema.json', jsonBlob(worldSchema)],
    ['schema/mapsoo-generation-receipt.schema.json', jsonBlob(generationReceiptSchema)],
  ]);
  initialPayloads.forEach((_blob, path) => assertSafePackPath(path));

  const initialEntries = await Promise.all(
    Array.from(initialPayloads, ([path, blob]) => payloadEntry(path, blob)),
  );
  const inputSpecRecord = initialEntries.find(({ path }) => path === worldSpecPath)?.record;
  if (!inputSpecRecord) throw new Error('Alpha.4 export is missing its serialized World Spec.');

  const projectedReceipt = projectTrustedGenerationReceipt(run, {
    path: inputSpecRecord.path,
    sha256: inputSpecRecord.sha256,
  });
  const receiptEntry = await payloadEntry('generation-receipt.json', jsonBlob(projectedReceipt));
  const entries = [...initialEntries, receiptEntry];
  const manifest = await buildAlpha4PackManifest({
    run,
    files: entries.map(({ record }) => record),
    receiptBytes: receiptEntry.bytes,
  });
  assertExactPayloadCoverage(entries, manifest.files);

  const manifestBytes = new TextEncoder().encode(`${JSON.stringify(manifest, null, 2)}\n`);
  const archiveEntries = [
    ...entries.map(({ path, bytes }) => ({ archivePath: `${rootName}/${path}`, bytes })),
    { archivePath: `${rootName}/${manifestPath}`, bytes: manifestBytes },
  ].sort((left, right) => comparePortablePaths(left.archivePath, right.archivePath));

  const zip = new JSZip();
  for (const { archivePath, bytes } of archiveEntries) {
    zip.file(archivePath, bytes, {
      binary: true,
      createFolders: false,
      date: ZIP_DATE,
      unixPermissions: 0o100644,
    });
  }

  const zipBytes = await zip.generateAsync({
    type: 'uint8array',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
    platform: 'UNIX',
    streamFiles: false,
  });
  const zipBuffer = new ArrayBuffer(zipBytes.byteLength);
  new Uint8Array(zipBuffer).set(zipBytes);
  return { filename, blob: new Blob([zipBuffer], { type: 'application/zip' }) };
}

export async function downloadAlpha4PortablePack(run: GenerationRunResult): Promise<void> {
  const pack = await buildAlpha4PortablePack(run);
  const url = URL.createObjectURL(pack.blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = pack.filename;
  try {
    link.click();
  } finally {
    revokeObjectUrlLater(url);
  }
}
