import { describe, expect, it } from 'vitest';
import { generateWorld } from './generate-world';
import { createGenerationRun, type GenerationRunResult } from './generation-evidence';
import { validateGenerationReceipt } from './generation-receipt';
import { runGenerationProviderWithEvidence, type GeneratorProvider } from './generation-provider';
import { DEFAULT_WORLD_SPEC } from './world-spec';
import { PROCEDURAL_PIXEL_PROVIDER } from '../providers/procedural-pixel-provider';
import { projectTrustedGenerationReceipt } from './trusted-generation-receipt';

const INPUT_SPEC = {
  path: 'worlds/sunny-meadow.world.json',
  sha256: 'a'.repeat(64),
};

async function trustedBuiltinRun(): Promise<GenerationRunResult> {
  return runGenerationProviderWithEvidence(PROCEDURAL_PIXEL_PROVIDER, DEFAULT_WORLD_SPEC, {
    now: () => new Date('2026-07-19T00:00:00.000Z'),
  });
}

describe('trusted generation receipt projection', () => {
  it('copies the runner-owned built-in evidence into the strict 0.2 contract', async () => {
    const run = await trustedBuiltinRun();
    const receipt = projectTrustedGenerationReceipt(run, INPUT_SPEC);

    expect(receipt).toEqual({
      schema_version: '0.2.0',
      created_at: '2026-07-19T00:00:00.000Z',
      world: {
        id: 'sunny-meadow',
        input_spec: INPUT_SPEC,
        seed: DEFAULT_WORLD_SPEC.seed,
      },
      provider: {
        id: 'procedural-pixel-v1',
        version: '0.1.0',
        execution: 'local',
        output_provenance: 'procedural',
      },
      model: null,
      workflow: {
        id: 'mapsoo-procedural-world-pack',
        version: '0.1.0',
        definition_sha256: null,
      },
      transformations: [
        { id: 'seeded-map-layout', version: '0.1.0' },
        { id: 'procedural-pixel-atlas', version: '0.1.0' },
        { id: 'png-rgba-export', version: '0.1.0' },
      ],
      ai_disclosure: {
        contains_generative_ai: false,
        human_curated: false,
        statement: null,
      },
      licensing: {
        output: { id: 'CC0-1.0', notice_path: 'license-assets.md' },
        provider_terms: null,
      },
      sources: [],
    });
    expect(validateGenerationReceipt(receipt, {
      world: run.world,
      inputSpec: INPUT_SPEC,
      createdAt: run.evidence.createdAt,
      provider: receipt.provider,
      outputLicense: { id: 'CC0-1.0', noticePath: 'license-assets.md' },
    })).toEqual([]);
  });

  it('rejects public factory results, clones, and bare generated worlds', async () => {
    const trusted = await trustedBuiltinRun();
    const directlyBuilt = createGenerationRun({
      world: trusted.world,
      requestSpec: trusted.world.spec,
      provider: trusted.evidence.provider,
      claims: {
        model: trusted.evidence.model,
        workflow: trusted.evidence.workflow,
        transformations: trusted.evidence.transformations,
        disclosureStatement: trusted.evidence.aiDisclosure.statement,
        providerTerms: trusted.evidence.providerTerms,
        sources: trusted.evidence.sources,
      },
      createdAt: trusted.evidence.createdAt,
    });

    expect(() => projectTrustedGenerationReceipt(directlyBuilt, INPUT_SPEC)).toThrow('evidence.untrusted-run');
    expect(() => projectTrustedGenerationReceipt({ ...trusted }, INPUT_SPEC)).toThrow('evidence.untrusted-run');
    expect(() => projectTrustedGenerationReceipt(
      generateWorld(DEFAULT_WORLD_SPEC) as unknown as GenerationRunResult,
      INPUT_SPEC,
    )).toThrow('evidence.untrusted-run');
  });

  it('projects AI disclosure and license evidence without leaking provider extension fields', async () => {
    const aiProvider: GeneratorProvider = {
      id: 'example-ai-provider',
      version: '1.0.0',
      displayName: 'Example AI Provider',
      capabilities: {
        ...PROCEDURAL_PIXEL_PROVIDER.capabilities,
        execution: 'remote',
        determinism: 'best-effort',
        requiresCredentials: true,
        outputProvenance: 'generative-ai',
      },
      async generate(spec) {
        const world = generateWorld(spec);
        world.generator = { id: 'example-ai-provider', version: '1.0.0' };
        return {
          world,
          claims: {
            model: { provider: 'Example AI', id: 'image-v1', revision: '2026-07-19' },
            workflow: {
              id: 'example-ai-workflow',
              version: '1.0.0',
              definition_sha256: 'b'.repeat(64),
            },
            transformations: [{ id: 'model-image-generation', version: '1.0.0' }],
            disclosureStatement: 'Generated by Example AI from a hashed workflow.',
            providerTerms: { url: 'https://example.com/terms', version: '2026-07' },
            sources: [],
          },
        };
      },
    };
    const run = await runGenerationProviderWithEvidence(aiProvider, DEFAULT_WORLD_SPEC, {
      now: () => new Date('2026-07-19T00:00:00.000Z'),
    });
    const receipt = projectTrustedGenerationReceipt(run, INPUT_SPEC);

    expect(receipt.provider).toEqual({
      id: 'example-ai-provider',
      version: '1.0.0',
      execution: 'remote',
      output_provenance: 'generative-ai',
    });
    expect(receipt.ai_disclosure).toEqual({
      contains_generative_ai: true,
      human_curated: false,
      statement: 'Generated by Example AI from a hashed workflow.',
    });
    expect(receipt.model).toEqual({ provider: 'Example AI', id: 'image-v1', revision: '2026-07-19' });
    expect(receipt.licensing.provider_terms).toEqual({
      url: 'https://example.com/terms',
      version: '2026-07',
    });
    expect(Object.keys(receipt.provider).sort()).toEqual([
      'execution',
      'id',
      'output_provenance',
      'version',
    ]);
  });
});
